### ISSUE TITLE
Unable to compile, receive error /usr/bin/ld: cannot find -lGL

### ISSUE THREAD

**Issue by skippy1976** [chebee7i/Vrui#1]
I am trying to build VRUI as part of the AR Sandbox build.  I"ve tried download VRUI seperatly and buidling but also still get the same error:

Building Vrui on 8 CPUs
---- Vrui configuration options: ----
Run-time library search paths enabled
Threads library has built-in thread-local storage
Threads library uses built-in atomics
Threads library uses POSIX spinlocks
Libusb library version 1.0 exists on host system
Realtime library uses timers
Multithreaded rendering disabled
Local pthread implements pthread_cancel
Libusb library supports bus topology queries
PNG image file format enabled
ALSA sound device support enabled
JPG image file format enabled
Spatial sound using OpenAL enabled
SPEEX speech compression support enabled
TIFF image file format disabled
Video4Linux2 video device support enabled
FireWire DC1394 video device support enabled
Theora video codec support enabled
Swapgroup support for Vrui windows disabled
Event device support for joysticks disabled
Vrui will save screenshots in PNG format
Bluetooth support (for Nintendo Wii controller) enabled
Support for spatial audio enabled
USB support (for Razer Hydra and Oculus Rift tracker) enabled
Support to save screen captures in Ogg/Theora format enabled
---- Vrui installation configuration ----
Root installation directory               : /home/haggerty/Vrui-3.1
Header installation root directory        : /home/haggerty/Vrui-3.1/include
Library installation root directory       : /home/haggerty/Vrui-3.1/lib/x86_64-linux-gnu
Executable installation directory         : /home/haggerty/Vrui-3.1/bin
Plug-in installation root directory       : /home/haggerty/Vrui-3.1/lib/x86_64-linux-gnu
Configuration file installation directory : /home/haggerty/Vrui-3.1/etc
Shared file installation root directory   : /home/haggerty/Vrui-3.1/share
Makefile fragment installation directory  : /home/haggerty/Vrui-3.1/share
Build system installation directory       : /home/haggerty/Vrui-3.1/share/make
pkg-config metafile installation directory: /home/haggerty/Vrui-3.1/lib/x86_64-linux-gnu/pkgconfig
Documentation installation directory      : /home/haggerty/Vrui-3.1/share/doc
---- End of Vrui configuration options ----
Linking /home/haggerty/src/Vrui-3.1-004/lib/x86_64-linux-gnu/libUSB.g++-3.so.3.1...
Linking /home/haggerty/src/Vrui-3.1-004/lib/x86_64-linux-gnu/libIO.g++-3.so.3.1...
Linking /home/haggerty/src/Vrui-3.1-004/lib/x86_64-linux-gnu/libGLWrappers.g++-3.so.3.1...
Creating application makefile fragment...
Creating configuration makefile fragment...
Creating pkg-config meta data file...
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
make: **\* [/home/haggerty/src/Vrui-3.1-004/lib/x86_64-linux-gnu/libGLWrappers.g++-3.so.3.1] Error 1
make: **\* Waiting for unfinished jobs....
Build unsuccessful; please fix any reported errors and try again

I am running on an i7 and with a NVIDIA GTX 870:

haggerty@haggerty-AR ~ $ inxi -Gx
Graphics:  Card: NVIDIA GM204 [GeForce GTX 970] bus-ID: 01:00.0
           Display Server: X.Org 1.17.1 drivers: nvidia (unloaded: fbdev,vesa,nouveau)
           Resolution: 1280x768@59.9hz
           GLX Renderer: GeForce GTX 970/PCIe/SSE2
           GLX Version: 4.5.0 NVIDIA 367.27 Direct Rendering: Yes
haggerty@haggerty-AR ~ $ 

Any thoughts?

**Comment by chebee7i** [comment]
The hint from the log is:

```
/usr/bin/ld: cannot find -lGL
```

Sounds like you need to make sure the install knows where you GL drivers are.  

Also, FYI...this repository is way out of date from the proper Vrui releases.  I put these up here because, at the time, there was no repository of Vrui available on any social coding site. That has changed now and you can find more updated versions here:  https://github.com/KeckCAVES/Vrui.  Though it seems to still be the case that development does not happen on any public repository.

See also the official download page:
http://idav.ucdavis.edu/~okreylos/ResDev/Vrui/

**Comment by skippy1976** [comment]
Thanks, I recognise the fact that it cannot find the GL library, even though it appears to be available and in the correct location.  I've asked the same question elsewhere but not got a response.  

Any indication or idea how I would resovle this?

Thanks
